services:
  web.api:
    container_name: WebApplication
    image: web.api:${TAG:-latest}
    build:
      context: .
      dockerfile: Web.Api/Dockerfile
    env_file:
      - .env
    environment:
      - DB_CONNECTION_STRING=Server=sql.service,1433;Database=ninisApp;User Id=sa;Password=${DB_CONNECTION_PASSWORD};TrustServerCertificate=True
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_BASE_URL=${AWS_BASE_URL}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}
    ports:
      - "5236:8080"
    depends_on:
      - sql.service
        
  sql.service:
    container_name: SqlDatabase
    image: mcr.microsoft.com/mssql/server:latest
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_CONNECTION_PASSWORD}
    restart: always
    ports:
      - "1433:1433"
      
